### ISSUE TITLE
Cannot launch Concern

### ISSUE THREAD

**Issue by segmentati0nf4ult** [combatopera/Concern#34]
Hi, I'm not being able to run Concern. I get this error message:

```$ Concern /usr/lib/python3.9/site-packages/FoxDot/demo
Traceback (most recent call last):
  File "/usr/bin/Concern", line 5, in <module>
    from concern.concern import main_Concern
  File "/home/user/.local/lib/python3.9/site-packages/concern/concern.py", line 26, in <module>
    from screen import stuffablescreen
  File "/home/user/.local/lib/python3.9/site-packages/screen.py", line 18, in <module>
    from lagoon import screen
ImportError: cannot import name 'screen' from 'lagoon' (/home/user/.local/lib/python3.9/site-packages/lagoon/__init__.py)
```

$ python -V
Python 3.9.6

**Comment by combatopera** [comment]
hi zephrax, Concern requires GNU Screen, which you'll need to install separately. it should be available via your linux distribution's package manager

**Comment by segmentati0nf4ult** [comment]
Hi @combatopera , I installed it an now it's working. Thanks!
